apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-planeta
  labels:
    app: frontend-planeta
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: frontend-planeta
  template:
    metadata:
      labels:
        deployment: frontend-planeta
    spec:
      containers:
        - name: frontend-planeta
          image: {{ .Values.environment.images.frontend }}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          securityContext:
            runAsUser: 0
            capabilities:
              drop:
                - MKNOD
          ports:
            - containerPort: 80
      serviceAccountName: planeta-dostup
      imagePullSecrets:
        - name: {{ .Values.environment.imagePullSecrets }}