kind: Service
apiVersion: v1
metadata:
  name: frontend-planeta
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    deployment: frontend-planeta
status:
  loadBalancer: {}