kind: Service
apiVersion: v1
metadata:
  name: planeta-postgresql
spec:
  ports:
    - name: 5432-tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    deployment: planeta-postgresql
status:
  loadBalancer: {}
