{{ if .Values.integration.settings.dependencies.postgresql }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "postgresql.resource.prefix" . }}-data-volume
  namespace : {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.integration.apps.postgresql.volume.capacity }}
  storageClassName: {{ .Values.integration.apps.postgresql.volume.storageClassName }}

{{ end }}