kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: planeta-export-api
spec:
  host: {{ .Values.environment.ISSUER }}
  path: /export_api/
  to:
    kind: Service
    name: planeta-gateway-service
  port:
    targetPort: 8080-tcp