kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: planeta-login
spec:
  host: {{ .Values.environment.ISSUER }}
  path: /login/
  to:
    kind: Service
    name: planeta-gateway-service
  port:
    targetPort: 8080-tcp