kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: planeta-process
spec:
  host: {{ .Values.environment.ISSUER }}
  path: /planeta-process
  to:
    kind: Service
    name: planeta-gateway-service
    weight: 100
  port:
    targetPort: 8080-tcp